config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'
  get 'about', to: 'pages#about'

  resources :articles

  get 'signup', to: 'users#new'
  resources :users, except: [:new]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :categories, except: [:destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  validates :title, presence: true , length: {minimum: 6 , maximum: 100}
  validates :description, presence: true , length: {minimum: 10  , maximum: 300 }	
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  before_save {self.email = email.downcase}
  has_many :articles

  validates :username,presence: true,
                      uniqueness: {case_sensitive: false},
                      length: {maximum: 105}


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	 
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update]

  def show
    
  end

  def index
    @articles = Article.all
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.user = User.first
    
    if @article.save
      flash[:notice] = "Article was created successfully"
      redirect_to @article
    else
      render :new
    end
  end  

  def update
   
    if @article.update(params.require(:article).permit(:title, :description))
      flash[:notice] = "Article was updated successfully"
      redirect_to @article
    else
      render 'edit'   
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to articles_path
  end
 private
  def set_article
    @article = Article.find(params[:id])
  end  

  def article_params
    params.require(:article).permit(:title, :description)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  def about 
  end  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new

  end

  def create
    user = User.find_by(email: params[:session][:email].downcase , password: params[:session][:password])

    if user
      session[:user_id] = user.id
      flash[:success] = "You have successfully logged in"
      redirect_to user_path(user)
    else
      flash.now[:danger] = "There was something wrong with your login information"
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "You have logged out"
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  before_action :require_admin, only: [:destroy]

  def index
    @users = User.paginate(page: params[:page], per_page: 5)
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "Welcome to the alpha blog #{@user.username}"
      redirect_to user_path(@user)
    else
      render 'new'
    end
  end
  
  def edit
  end
  
  def update
    if @user.update(user_params)
      flash[:success] = "Your account was updated successfully"
      redirect_to articles_path
    else
      render 'edit'
    end
  end
  
  def show
    @user_articles = @user.articles.paginate(page: params[:page], per_page: 5)
  end
  
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:danger] = "User and all articles created by user have been deleted"
    redirect_to users_path
  end
  
  private
  def user_params
    params.require(:user).permit(:username, :email, :password)
  end
  def set_user
    @user = User.find(params[:id])
  end
  
  def require_same_user
    if current_user != @user and !current_user.admin?
      flash[:danger] = "You can only edit your own account"
      redirect_to root_path
    end
  end
  
  def require_admin
    if logged_in? and !current_user.admin?
      flash[:danger] = "Only admin users can perform that action"
      redirect_to root_path
    end
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user, options = { size: 80})
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class: "img-circle")
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_article.html.erb
<div id="1">
  <p>
    <strong>Title:</strong>
    <%= article.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= article.description %>
  </p>

</div>

app/views/articles/_form.html.erb
<%= form_with(model: @article) do |form| %>
  <% if @article.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this @article from being saved:</h2>

      <ul>
        <% @article.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit article</h1>

<% if @article.errors.any? %>
  <h2>The following errors prevented the article from being saved </h2>
  <ul>
    <% @article.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>
  

<%= form_with(model: @article, local: true)  do |f| %>

  <p>
    <%= f.label :title %><br/>
    <%= f.text_field :title %>
  </p>
  
  <p>
  	<%= f.label :description %><br/>
  	<%= f.text_area :description %>
  </p>  

  <p>
    <%= f.submit %>
  </p>  

<% end %>


<%= link_to 'Cancel and return to articles listing', articles_path %>

app/views/articles/index.html.erb
<h1>Articles listing page</h1>
<table class="table table-light" >
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Title</th>
      <th scope="col">Description</th>
      <th scope="col">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <th scope="row"><%= article.id %></th>
        <td><%= article.title %></td>
        <td><%= article.description %></td>
        <td><%= link_to 'Show', article_path(article) %>
        <%= link_to 'Edit', article_path(article) %>
        <%= link_to 'Delete', article, method: :delete, data: {confirm: "Are you sure?"} %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'Create new article', new_article_path %> 

app/views/articles/new.html.erb
<h1>Create a new article</h1>

<% if @article.errors.any? %>
  <h2>The following errors prevented the article from being saved </h2>
  <ul>
    <% @article.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>
  

<%= form_with scope: :article, url: articles_path, local: true do |f| %>

  <p>
    <%= f.label :title %><br/>
    <%= f.text_field :title %>
  </p>
  
  <p>
  	<%= f.label :description %><br/>
  	<%= f.text_area :description %>
  </p>  

  <p>
    <%= f.submit %>
  </p>  

<% end %>
<%= render 'form' %>

<%= link_to 'Return to articles listing', articles_path %>

app/views/articles/show.html.erb
<h2 align="center">Title: <%= @article.title %></h2>
<div class="container">
	<div class="row justify-content-md-center">
		<div class="col-8 col-4">
			<div class="card text-center shadow mb-5 bg-white rounded">
				<div class="card-header font-italic">
					by KomalDevi
				</div>
				<div class="card-body">
          <div class="card-text text-left"><%= simple_format(@article.description) %></div>
          <%= link_to "Edit this article", edit_article_path(@article), class: "btn btn-xs btn-primary" %>
          <%= link_to "Delete this article", article_path(@article),method: :delete,data: {confirm: "Are you sure?"},class: "btn btn-xs btn-danger" %>
        </div>
        <div class="card-header font-italic">
          <%= time_ago_in_words(@article.created_at) %> Ago, Edited <%= time_ago_in_words(@article.updated_at) %> Ago
        </div>
			</div>
		</div>
	</div>
</div>

app/views/layouts/_footer.html.erb
<footer id="sticky-footer" class="text-center text-white fixed-bottom" style="background-color: #45637d;">
  <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
    ©2023 Copyright:
    <a class="text-white" href="https://www.rvjtech.net/"> RVJ INFOTECH 2021. Made with </a>
  </div>
</footer>

app/views/layouts/_nav_bar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
   <%= link_to "Home", posts_path, class:"navbar_brand", style:"margin-left: 20px;" %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent", style= "margin-left:20px;">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">

       </li>
      <li class="nav-item">
        <%= link_to "Upload Post", new_post_path, class: "nav_link" %>
      </li>

      <li class="nav-item">
       <%= link_to "About Page", home_about_path, class: "nav_link"%>
      </li>

      <% if user_signed_in? %>
      <li class="nav-item">
       <%= link_to "Sign out", destroy_user_session_path, class:"nav_link" %>
      </li>
     <li class="nav-item">
       <%= link_to "View my Posts", posts_mypostsS_path, class:"nav_link" %>
      </li>

      <% else %>


      <li class="nav-item">
       <%= link_to "Sign Up", new_user_registration_path, class:"nav_link"%>
      </li>
      <% end %>
      <li class="nav-item">
       <%= link_to "Edit Account", edit_user_registration_path, class:"nav_link" %>
      </li>

    </ul>

  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Alpha Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <%= javascript_importmap_tags %>
  </head>

  <body>

    <%= yield %>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>

<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>


    <%= render "layouts/footer"%>
  </body>
</html>

app/views/pages/about.html.erb
<h1> Welcome to about page </h1>
<%= link_to 'Articles listing', articles_path %>
<%= link_to 'Home page', root_path %>

app/views/pages/home.html.erb
<div class="page-content"></div>
<div class="container" id="home-container">
	<div class="jumbotron text-center text-white">
	  <h1 class="display-4">RVJ Infotech</h1>
	  <p class="lead">We love crafting beautiful,smart and inspired work that is focused on a business'goals and their customers.We do this across multiple touch points to help organizations like yours acheive their goal.</p>
	  <hr class="my-4">
	  <p>We live our values.innovation,Respect for Teamwork,Respect for Customers and Respect for quality.</p>
	  <p class="lead">
	    <%= link_to "Sign Up!", login_path, class:"btn btn-success btn-lg"%>
	  </p>
	</div>
</div>
<%= link_to 'Articles listing', articles_path %>
<%= link_to 'About page', about_path %>

app/views/users/show.html.erb
<h1 align="center">Welcome to <%= @user.username %>'s page</h1>
<div class="row">
  <div class="col-md-4 col-md-offset-4 center">
    <%= gravatar_for @user, size: 150 %>
  </div>
</div>
<h4 align="center"><%= @user.username %>'s articles</h4>
<div class="center">
  <%= will_paginate @user_articles %>
</div>
<% @user_articles.each do |article| %>
  <%= render 'articles/article', article: article %>
<% end %>
<div class="center">
  <%= will_paginate @user_articles %>
</div>